[build]
  base    = "ui"
  publish = "ui/build"
  command = "npm run build"

# COMMENT: This a rule for Single Page Applications
# https://www.netlify.com/docs/redirects/#structured-configuration
# https://www.netlify.com/docs/redirects/#history-pushstate-and-single-page-apps
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200